services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotfiles-emacs-dev-container
    volumes:
      - type: bind
        source: "../../.emacs.d"
        target: "/home/ubuntu/.emacs.d"
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: "../../"
        target: "/workspace"
    environment:
      DISPLAY: $DISPLAY
    tty: true
