# difft
- name: check difft command
  ansible.builtin.command: which difft
  register: which_difft
  failed_when: false
  changed_when: false

- name: setup difft command
  become: false
  when: which_difft.rc != 0
  block:
    - name: download difftastic
      ansible.builtin.get_url:
        url: https://github.com/Wilfred/difftastic/releases/download/0.67.0/difft-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/difftastic.tar.gz

    - name: install difftastic
      ansible.builtin.unarchive:
        src: /tmp/difftastic.tar.gz
        # NOTE: only contains "difft" file
        dest: "{{ lookup('env','HOME') }}/.local/bin/"

- name: verify difft command
  ansible.builtin.command: which difft
  changed_when: false
