# rust toolchain
- name: setup rust toolchain
  become: false
  block:
    - name: install rustup and rust toolchain
      ansible.builtin.shell: >-
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ lookup('env','HOME') }}/.cargo/bin/rustc"
