- name: install gui tools on baremetal
  when: not is_ci
  apt:
    name:
      - vlc
      - simplescreenrecorder
      - gparted
      - flameshot
    state: present

- name: check gui tools installability on ci
  when: is_ci
  apt:
    name:
      - vlc
      - simplescreenrecorder
      - gparted
      - flameshot
    state: present
    check_mode: true
