- hosts: localhost
  become: true
  vars_files:
    - vars/versions.yaml
  vars:
    # directories where the commands installed by this playbook are placed
    extra_paths:
      - "{{ lookup('env','HOME') }}/.local/bin"
      - "{{ lookup('env','HOME') }}/.cargo/bin"
      - "{{ lookup('env','HOME') }}/.bun/bin"
      - "{{ lookup('env','HOME') }}/.devcontainers/bin"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ extra_paths | join(':') }}"
  roles:
    - role: init_snap
    - role: xdg_base_directory
      tags: [for_devcontainer]
    - role: dot_rc
      tags: [for_devcontainer]
    - role: system_tools
    - role: terminal
      tags: [not_for_wsl]
    - role: emacs
    - role: dev_tools
    - role: fonts
    - role: gui_tools
      tags: [not_for_wsl]
