- hosts: localhost
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ lookup('env','HOME') }}/.local/bin"
  roles:
    - role: init_snap
    - role: xdg_base_directory
      tags: [for_devcontainer]
    - role: dot_rc
      tags: [for_devcontainer]
    - role: system_tools
    - role: terminal
      tags: [not_for_wsl]
    - role: editor
    - role: dev_tools
    - role: fonts
    - role: gui_tools
      tags: [not_for_wsl]
