- name: install fonts if not ci
  when: not is_ci
  apt:
    name:
      - fonts-powerline
      - fonts-takao-gothic
      - fonts-takao-pgothic
      - fonts-firacode
    state: present

- name: check fonts installability on ci
  when: is_ci
  apt:
    name:
      - fonts-powerline
      - fonts-takao-gothic
      - fonts-takao-pgothic
      - fonts-firacode
    state: present
  check_mode: true

- name: install Moralerspace font
  when: not is_ci # this font file is large
  block:
    - name: download Moralerspace zip file
      ansible.builtin.get_url:
        url: https://github.com/yuru7/moralerspace/releases/download/v2.0.0/MoralerspaceHW_v2.0.0.zip
        dest: /tmp/MoralerspaceHW.zip

    - name: unarchive Moralerspace zip file
      ansible.builtin.unarchive:
        src: /tmp/MoralerspaceHW.zip
        dest: /usr/local/share/fonts/
        include:
          - MoralerspaceHW_v2.0.0/MoralerspaceNeonHW-Regular.ttf
          - MoralerspaceHW_v2.0.0/MoralerspaceNeonHW-Bold.ttf
          - MoralerspaceHW_v2.0.0/MoralerspaceNeonHW-Italic.ttf
          - MoralerspaceHW_v2.0.0/MoralerspaceNeonHW-BoldItalic.ttf

    - name: update cache after Moralerspace
      ansible.builtin.shell: fc-cache -vf
