name: ansible-ci

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ansible-test:
    name: "${{ matrix.os }} / ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04

        include:
          - name: default
            playbook_opts: ""

          - name: for_devcontainer
            playbook_opts: "--tags for_devcontainer"

          - name: skip_not_for_wsl
            playbook_opts: "--skip-tags not_for_wsl"

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup uv
        uses: astral-sh/setup-uv@v7

      - name: install python
        run: uv python install # NOTE: from .python-version

      - name: install packages
        run: uv sync

      - name: run playbook
        run: |
          uv run ansible-playbook ansible/playbook.yaml -e is_ci=true -v ${{ matrix.playbook_opts }}
